image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - akamud.vscode-theme-onedark
    - ms-vscode-remote.remote-containers
    - usernamehw.errorlens
    - alexisvt.flutter-snippets
    - akamud.vscode-theme-onedark
    - alexisvt.flutter-snippets
    - Blackboxapp.blackbox
    - chrmarti.regex
    - Dart-Code.dart-code
    - Dart-Code.flutter
    - eamodio.gitlens
    - formulahendry.code-runner
    - GitHub.codespaces
    - GitHub.copilot
    - GitHub.copilot-labs
    - GitHub.vscode-pull-request-github
    - gitpod.gitpod-remote-ssh
    - golang.go
    - herbertagosto.skill
    - jock.svg
    - ms-azuretools.vscode-docker
    - ms-python.python
    - ms-python.vscode-pylance
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - PKief.material-icon-theme
    - rangav.vscode-thunder-client
    - rashwell.tcl
    - redhat.vscode-yaml
    - ritwickdey.LiveServer
    - rust-lang.rust-analyzer
    - usernamehw.errorlens
    - VisualStudioExptTeam.intellicode-api-usage-examples
    - vscode-icons-team.vscode-icons
    - wavetrace.wavetrace
    - zhuangtongfa.material-theme
    - zhuangtongfa.One-dark-pro
